### ISSUE TITLE
Can Mesh2HRTF calculate open canal mesh?

### ISSUE THREAD

**Issue by May-SC** [Any2HRTF/Mesh2HRTF#102]
Mesh2HRTF toolbox is very useful that helps me a lot. Thank you very much!
I have a question about if it can calculate open canal mesh. Put the microphone at the center of the end of the ear canal . Have you verified it?

**Comment by petibub** [comment]
Thanks a lot! 

If the ear canal is modeled as a (closed) mesh and one of its element is chosen as a virtual microphone, Mesh2HRTF can calculate the transfer functions. We actually will show this ability at the upcoming Forum Acusticum. But...

> Have you verified it?

... unfotunately I am not aware of any verifications re acoustic measurements.

**Comment by germknoedlspeck** [comment]
Hi @May-SC,

thank you for reaching out. As @petibub already mentioned, we will publish our results at Forum Acusticum. At the same conference, a colleague will present the validation of the calculated results with measurements :)

**Comment by SDX-LV** [comment]
Very interesting topic.
I found a commercial place where I could get partial ear-canal 3D scan using Otoscan 3D scanner https://youtu.be/2qcvW7_PYyM
Scan is not all the way to the eardrum, but should get 3D mesh of more than half of the ear-canal depth.

Together with some rough head scan using any other 3D scanner this should give deeper and very accurate outer ear 3D data, but not sure if it will make an audible difference compared to simple scanning with an iPhone or other means. :)

**Comment by May-SC** [comment]
Hi.
I have a mesh with the ear canal which is caught by MRI (magnetic resonance imaging). So I want use Mesh2HRTF to calculate HRTF when the microphone is put near the drum.  

> You have to be careful with the microphone placement, because the eardrum is at the end of the ear canal, but rather pointing upwards (it is not a strictly vertical membrane).
As you said, the ear canal is curved.  Now, I put the microphone point at the end of canal.  What should to be careful when the ear canal points upward?

> As @petibub already mentioned, we will publish our results at Forum Acusticum. At the same conference, a colleague will present the validation of the calculated results with measurements :)
Is the simulation and validation results of the model with ear canal coming soon?
I'm looking forward to it!
