### ISSUE TITLE
finalize_hrtf_simulation.py error.

### ISSUE THREAD

**Issue by abidshahriar** [Any2HRTF/Mesh2HRTF#103]
I am getting an error like this finalize_hrtf_simulation.py. Any advice would be appreciated.[
![9C7F3A86-C4B8-47A1-B85B-F47D0C76D3D7](https://github.com/Any2HRTF/Mesh2HRTF/assets/64680295/d3df69f4-1573-43d7-aabd-2687237f0ef0)
](url)

**Comment by germknoedlspeck** [comment]
Hi @abidshahriar,

did you resolve the error or did you close the issue unintended?

**Comment by abidshahriar** [comment]
Hi @germknoedlspeck  ,
Yes, very happy to resolve the error and finally been able to export my first SOFA ^_^ Cheers ! Thank you.

What i did was i resolved the inverted comma in like this:(  Mesh2HRTF_version = '1.0.0-dev'  ) in Output@HRTF.py file that solved the Syntax error. And the error that was showing in Traceback for that i have removed an extra parameter 'version' in sofa_write function. Worked like a charm.

**Comment by germknoedlspeck** [comment]
Excellent, I'm happy to hear that!
Thank you for including the solution that worked for you. If people in the future have the same problem, we can point them to this issue thread 👍
