### ISSUE TITLE
unhandled std::bad_alloc

### ISSUE THREAD

**Issue by chris-hld** [Any2HRTF/Mesh2HRTF#104]
Some instances may fail with

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/sh: line 1: 69311 Aborted                 /scratch/work/holdc1/HUBSI/Mesh2HRTF/mesh2hrtf/NumCalc/bin/NumCalc -istart 94 -iend 94 > NC94-94_log.txt
```

Not sure where exactly this occurs, but I'll report it here for reference.
It might be also possible to handle this from the outside, i.e. in `manage_numcalc()`.

**Comment by f-brinkmann** [comment]
Might this be a memory issue on the cluster? Can you maybe post or send me *NC94-94_log.tx*, *manage_numcalc_xxx.txt*

**Comment by chris-hld** [comment]
Seems resolved. Increasing the wait time to 60s in combination with the improved RAM handling seems to fix the issue.

**Comment by f-brinkmann** [comment]
Thanks for checking. I added some more information to the docstring in the hope that it will be easier to catch/understand for others if this issue comes up.
