### ISSUE TITLE
Output2HRTF/Matlab: read frequency vector from Info.txt rather than fe.out files

### ISSUE THREAD

**Issue by germknoedlspeck** [Any2HRTF/Mesh2HRTF#11]
In a recent NumCalc update, frequencies will not be written in the NumCalc/source_N/fe(*).out director[y/ies]. Thus, the frequency vector should be read from Info.txt

**Comment by germknoedlspeck** [comment]
@f-brinkmann @schaastrommla in order to avoid numerical errors (Matlab using double precision, and Info.txt showing only 6 decimal places), should we read the frequency vector entries from NC.inp?

**Comment by f-brinkmann** [comment]
I also thought about this but went for the quick solution. Using NC.inp would indeed be more accurate at least in some cases!
