### ISSUE TITLE
How can i extract data and make whisker plot (so i can compare data) from generated .sofa  file?

### ISSUE THREAD

**Issue by abidshahriar** [Any2HRTF/Mesh2HRTF#112]
Hi, please let me know if there is any technique

**Comment by petibub** [comment]
Maybe this helps: https://link.springer.com/chapter/10.1007/978-3-030-00386-9_5
There, we discuss similar graphs. The PDF can be found here: https://www.researchgate.net/publication/330382764_Formation_of_three-dimensional_auditory_space

**Comment by petibub** [comment]
It looks like you need more support. 
If your project is educational, I think that this is a right moment to talk to your advisor to get more support. 
If your project is commercial, we can setup a supporting contract. Let me know if wish further support in this direction.
