### ISSUE TITLE
Mesh2HRTF HRTF Project Export issue

### ISSUE THREAD

**Issue by leverscut1** [Any2HRTF/Mesh2HRTF#115]
I am writing to seek assistance regarding an issue I encountered while running the script provided in the Mesh2HRTF GitHub repository.

I followed the steps outlined in the "Final export from Blender" section of the Basic Project export wiki (https://github.com/Any2HRTF/Mesh2HRTF/wiki/Basic_Project_export). However, I encountered an error that prevented the script from running successfully. The error message is as follows:

AttributeError: Calling operator "bpy.ops.mesh2input.inp" error, could not be found

I would greatly appreciate any guidance or assistance you can provide to help resolve this issue. If there are any additional steps or modifications needed to make the script work, please let me know.

Thank you very much for your time and assistance.

**Comment by f-brinkmann** [comment]
This most likely means that you are not providing the correct path to your Mesh2HRTF folder. You have to install the Addon in Blender and provide the path to your Mesh2HRTF folder. You can do this by changing the `programPath` variable as suggested in the [Blender export](https://github.com/Any2HRTF/Mesh2HRTF/wiki/Installation) documentation or providing the path in the field *Mesh2HRTF-path* during the export in Blender. If you are new to Mesh2HRTF our [free paper](https://doi.org/10.17743/jaes.2022.0078) might help to get a good overview
