### ISSUE TITLE
PPM related issue

### ISSUE THREAD

**Issue by leverscut1** [Any2HRTF/Mesh2HRTF#117]
hello, everyone.
I have read "Blender Add-on for the Registration of Parametric Pinna Model for Personalized Binaural Audio" and interested in PPM mentioned in this article, but I noticed that this project maybe removed from ANY2HRTF. 
How can I access to it?

**Comment by f-brinkmann** [comment]
... and also not part of mesh2hrtf - so I'm closing it for now.
