### ISSUE TITLE
manage_numcalc_script.py crashes immediately

### ISSUE THREAD

**Issue by mAjorHon** [Any2HRTF/Mesh2HRTF#118]
Hello.
When I run manage_numcalc_script.py, the CMD window crashes immediately. I tried running - run_NumCalc_instance.bat and checked the NC-1.out file. Only "No input file found!" It seems that NumCalc.exe is running fine? I don't know what to do next.

**Comment by f-brinkmann** [comment]
This indicates that the path to your project is not correct or that the project folder was not created correctly. But it seems you are following the workflow from https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/NumCalc_WindowsExe/ and should post your issue there. Unfortunately we don't have the time to support Windos and alternative workflows.

**Comment by mAjorHon** [comment]
> This indicates that the path to your project is not correct or that the project folder was not created correctly. But it seems you are following the workflow from https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/NumCalc_WindowsExe/ and should post your issue there. Unfortunately we don't have the time to support Windos and alternative workflows.

Thanks I just sovle the problem.It is because the VC++  library is missing that the installation is incomplete.

I can run it now, but I'm getting a new problem.
When I run manage_numcalc_script.py, the CMD window still crashes .but I got a file "manage_numcalc_xx_xx_xx.txt" this time.

Starting manage_numcalc with the following arguments [Feb 21 2024, 21:18:20]
----------------------------------------------------------------------------
project_path: E:\Mesh2Hrtftools
numcalc_path: Searching for NumCalc_WindowsExe
max_ram_load: 63.91 GB (63.91 GB detected, 54.43 GB available)
ram_safety_factor: 1.05
max_cpu_load: 90 %
max_instances: 16 (16 cores detected)
wait_time: 15 seconds
starting_order: alternate
confirm_errors: True

NumCalc executable: E:\Mesh2Hrtftools\NumCalc_WindowsExe\NumCalc.exe


Per project summary of instances that will be run
-------------------------------------------------
Detected 2 Mesh2HRTF projects in
E:\Mesh2Hrtftools

Obtaining RAM estimates for E:\Mesh2Hrtftools\myHRTF_project_L\NumCalc\source_1


I haven't seen a similar solution in Touble shooting.

**Comment by f-brinkmann** [comment]
I'm sorry but I never ran NumCalc under Windows. I reopen this issue in case any Windows users may jump in for help. Another option might be to build a Docker container using the dockerfile contained in the Mesh2HRTF repository and run NumCalc inside the container....

**Comment by mAjorHon** [comment]
> I'm sorry but I never ran NumCalc under Windows. I reopen this issue in case any Windows users may jump in for help. Another option might be to build a Docker container using the dockerfile contained in the Mesh2HRTF repository and run NumCalc inside the container....

Sorry, it's my silly mistake. I ran it in "administrator mode". It's fine when I turn it off
