### ISSUE TITLE
finalize_hrtf_simulation issue

### ISSUE THREAD

**Issue by mAjorHon** [Any2HRTF/Mesh2HRTF#119]
I finally finished the NumCalc_Simulation.
When I start the finalize_hrtf_simulation, many errors appear.
[error on windows.txt](https://github.com/Any2HRTF/Mesh2HRTF/files/14420558/error.on.windows.txt)

I also tried running it on Mac, and this is the full error information：
[error on Mac.txt](https://github.com/Any2HRTF/Mesh2HRTF/files/14420246/error.on.Mac.txt)

Ignoring the Non-Convergence issue for now, I think I can deal with it by the troubleshooting page. But I don't know how to deal with other problems. Can anyone help?

**Comment by f-brinkmann** [comment]
This is not part of mesh2hrtf. Please post your issue at https://sourceforge.net/projects/mesh2hrtf-tools/
