### ISSUE TITLE
This is about mesh2hrtf_inspection_sofa_files [Mesh2HRTF Python API]

### ISSUE THREAD

**Issue by kangminheo-cpf20e** [Any2HRTF/Mesh2HRTF#120]
Using mesh2hrtf, we are visualizing HRTF by obtaining it.
I'm working on it using the mesh2hrtf_inspection_sofa_files code, but the 3D,2D plot for the horizontal plane is drawn well, but it's not drawn well for the main, front plane, and I get the following error message. How can I use the mesh2hrtf_inspection_sofa_files code for the front, main plane?
![error_message_1](https://github.com/Any2HRTF/Mesh2HRTF/assets/70652469/906beb5a-10ab-4984-8d01-bbe78f5536da)
![error_message_2](https://github.com/Any2HRTF/Mesh2HRTF/assets/70652469/8992d296-6443-4981-8e0d-3e27234ee379)

**Comment by f-brinkmann** [comment]
Thanks for reporting this is a bug in mesh2hrtf and requries an update to work with the latest pyfar version. Unfortunately I wont be able to fix is in the next weeks. For now, a workaround would be to work with pyfar<0.6 by installing

`pip install pyfar<0.6` in your environment.

**Comment by f-brinkmann** [comment]
this is fixed in Mesh2HRTF v1.1.2
