### ISSUE TITLE
SOFA_myHRTF_project_merged

### ISSUE THREAD

**Issue by pleniera** [Any2HRTF/Mesh2HRTF#121]
![pb_3DHRTF](https://github.com/Any2HRTF/Mesh2HRTF/assets/144926950/ef5e1045-5e65-4dd7-b150-20efa0701325)
Hello, 
Affter computing the finalize_hrtf_simulation.py file I obtain such folder with all these files but I don't have any 3D HRTF in .png format . 
I don't understand why and what I did wrong ? And I didn't read any issues of this kind in the GIT tutorial.
Could you help me please ?
Thank you.

**Comment by f-brinkmann** [comment]
`finalize_hrtf_simulation` is not part of Mesh2HRTF and we can't support questions for this. It is a convenient but very specific workflow. If you want a more flexible workflow, please refer to the [official documentation](https://github.com/Any2HRTF/Mesh2HRTF/wiki/Mesh2HRTF-1.x) and [Mesh2HRTF Python API](https://mesh2hrtf.readthedocs.io/en/latest/)
