### ISSUE TITLE
Head transfer function Low frequency domain analysis questions

### ISSUE THREAD

**Issue by kangminheo-cpf20e** [Any2HRTF/Mesh2HRTF#122]
I'm going to use mesh2HRTF to interpret the low frequency range of HRTF, 0-5000 Hz (step:100 Hz).

However, the interpretation results are strange.
As shown in the attached picture, the time response also does not look like an impulse and keeps vibrating. Also, the frequency response comes out weird.

Why is this happening? Please tell me how to solve it.

I'll put the blenderfile, export code, and interpretation results that I interpreted on the Google Drive link. What am I doing wrong?

https://drive.google.com/drive/folders/12LOyPKFBwOZhSB0Pb8bxpR_9Gbv-RFbi?usp=sharing

[HRIR_ARI_10000_2D.pdf](https://github.com/Any2HRTF/Mesh2HRTF/files/15039494/HRIR_ARI_10000_2D.pdf)
[HRIR_Default_10000_2D.pdf](https://github.com/Any2HRTF/Mesh2HRTF/files/15039495/HRIR_Default_10000_2D.pdf)

**Comment by f-brinkmann** [comment]
I see that your HRTFs contain extremely large values at high frequencies. This is usually a sign for errors in the mesh (e.g., too large edge lengths). I would first try to compute only up to a frequency where these values do not occur.

**Comment by kangminheo-cpf20e** [comment]
I modified the mesh file using 'hrtf_mesh_grading_WindowsExe', and the settings are as follows.
"bin\hrtf_mesh_grading -x 0.5 -y 10 -v -h 0.20 -s "left" -i 3Dmesh_orig.stl -o 3Dmesh_graded_left.ply

bin\hrtf_mesh_grading -x 0.5 -y 10 -v -g 0.20 -s "right" -i 3Dmesh_orig.stl -o 3Dmesh_graded_right.ply
"

Is there anything wrong here by any chance?

**Comment by kangminheo-cpf20e** [comment]
I modified the mesh file using 'hrtf_mesh_grading_WindowsExe', and the settings are as follows.
"bin\hrtf_mesh_grading -x 0.5 -y 10 -v -h 0.20 -s "left" -i 3Dmesh_orig.stl -o 3Dmesh_graded_left.ply

bin\hrtf_mesh_grading -x 0.5 -y 10 -v -g 0.20 -s "right" -i 3Dmesh_orig.stl -o 3Dmesh_graded_right.ply
"

Is there anything wrong here by any chance?

**Comment by f-brinkmann** [comment]
It might, but its hard to say without seeing the mesh and the result...

**Comment by f-brinkmann** [comment]
Closed due to inacitivity
