### ISSUE TITLE
manage_numcalc_script.py can't estimate RAM 

### ISSUE THREAD

**Issue by ardev-ardev** [Any2HRTF/Mesh2HRTF#123]
When I export the project through Blender and select mm as Unit , manage_numcalc_script.py can't estimate RAM and throw the error below:
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'C:\mesh2hrtf-tools\NumCalc_WindowsExe\NumCalc.exe -estimate_ram' returned non-zero exit status 1.

In mesh2HRTF docs you can find https://github.com/Any2HRTF/Mesh2HRTF/wiki/Mesh2HRTF_Export_Parameters  : 
Unit: tells Mesh2HRTF, if the unit of your scene/project is millimeters (mm) or meters (m). 

Unit of my blender scene is meters (m) , so I change it to mm and the issue is still there .

On the other hand, when I use Unit in meters to export the project the error disappear and everything works as expected

**Comment by f-brinkmann** [comment]
Hi, I'm not sure if I understand the issue. Everything works correct if you are exporting with the correct unit, right? If this is the case things are fine from my point of view. It's not suprising that things do not work if the data is inconsistent due to an export with wrong parameters.

**Comment by ardev-ardev** [comment]
Hi, everything works correct if I only export the project using meters as unit , when I export the project in milimeters the above error occurs, even though I change the Scene unit in Blender to milimiters.

**Comment by f-brinkmann** [comment]
Ah, I see. I assume the scene unit in Blender is an information that does not change the data in the scene. That is, if you set the Blender unit from meter to militmeter the coordinates of your mesh vertices are not changed, but that is what Mesh2HRTF would expect.

Would it be more clear, if we change the description of *Unit* property in the Mesh2HRTF export from *'Unit of the 3D scene.'* to *'Unit of the Reference mesh. If the y-coordinate of the left ear channel entrance is at approx. 66 the unit is mm. If it is at approx. 0.066 the unit is m'*.

**Comment by ardev-ardev** [comment]
Yes , I'm agree 100 %, it will definitely be more clear  that way. Thanks for the reply! (:
