### ISSUE TITLE
spectral notch / frequency notch

### ISSUE THREAD

**Issue by pleniera** [Any2HRTF/Mesh2HRTF#132]
Hello, I would like to extract the values of the frequency and magnitude for the lowest and highest peaks on the 2D HRTFs that I obtained with mesh2hrtf. Do you know how can I get them ? 
Is there a complete table with the magnitude (in dB) computed for each frequency ?
Otherwise is it possible to print the 2D HRTFs for only one ear and not both on a single graph ?

Thank you !

**Comment by f-brinkmann** [comment]
Hi - the complete HRTFs and HRIR are contained in the SOFA files. In case you are using Python, you can read, process, and plot them with [pyfar](https://pyfar.org)

**Comment by f-brinkmann** [comment]
You can find examples on how to work with pyfar on the hompage linked above. Another possibility would be to open the SOFA file in any NetCDF viewer. But that might be equally cumbersome.

**Comment by pleniera** [comment]
Yes thank you, I read the different examples. But I don't find how to extract the coordinates (frequency and magnitudes) for each points of a 2D HRTF plot, generated with the mesh2hrtf algo...
