### ISSUE TITLE
Inquiry on Reusing Surface Sound Pressure for Evaluation Grid Points

### ISSUE THREAD

**Issue by leverscut1** [Any2HRTF/Mesh2HRTF#134]
Hello,

I am working on a project involving sound source and head model simulations using Mesh2HRTF. Specifically, I can compute the surface sound pressure for a given sound source and head model. I want to leverage this surface sound pressure to subsequently compute the sound pressure at evaluation grid points, without having to recalculate the surface sound pressure each time.

Is it possible to implement such a functionality? Any guidance or suggestions on how to approach this would be greatly appreciated.

Q:
Can the surface sound pressure be reused for different evaluation grid points?
What would be the best approach to implement this functionality?
Are there any existing tools or libraries that support this kind of operation?
Thank you in advance for your help!

Best regards

**Comment by leverscut1** [comment]
> Hello,
> 
> I am working on a project involving sound source and head model simulations using Mesh2HRTF. Specifically, I can compute the surface sound pressure for a given sound source and head model. I want to leverage this surface sound pressure to subsequently compute the sound pressure at evaluation grid points, without having to recalculate the surface sound pressure each time.
> 
> Is it possible to implement such a functionality? Any guidance or suggestions on how to approach this would be greatly appreciated.
> 
> Q: Can the surface sound pressure be reused for different evaluation grid points? What would be the best approach to implement this functionality? Are there any existing tools or libraries that support this kind of operation? Thank you in advance for your help!
> 
> Best regards

Example Workflow
Input: A file with field point coordinates.
Process:
Load precomputed surface sound pressure data.
Read field point coordinates from the input file.
Compute sound pressure at each field point using the surface sound pressure data.
Output: Sound pressure values at the specified field points.

**Comment by f-brinkmann** [comment]
That should be possible due to this 628b75bf9320cd3e2b751ef9797dd9cd213a4a1d but its not integrated and requires manual editing of the NC.inp files. But principally everything you need should be documented in the wiki. If you want to continue implementing it, we're happy to discuss options. @schaastrommla is that feature fully implemented in NumCalc? I did not find a documentation of it when calling `NumCalc -h`

**Comment by f-brinkmann** [comment]
closing this in favor of #85

**Comment by leverscut1** [comment]
Thanks for answering my questions. Best regards
