### ISSUE TITLE
manage_numcalc_script file

### ISSUE THREAD

**Issue by Pishisara** [Any2HRTF/Mesh2HRTF#139]
Hello,

I followed the tutorials from the videos.

**When I double-click on the manage_numcalc_script file, it doesn't give outputs 1 to 6 for both the left and right folders, but it does for the outputs from 7 to 160.**

![image](https://github.com/user-attachments/assets/b3538d7e-c280-4cdb-88e9-70b1e63e27a6)

And when I move the folders to finalize_HRTF_simulation, it shows this message:

![IMG_9163](https://github.com/user-attachments/assets/4dff04ba-bb2b-41ec-b3ba-9b1fd87e2c2a)
![IMG_9164](https://github.com/user-attachments/assets/9f55da5e-a3da-459c-a389-2b8118f6a48f)

Please help me with this.

[NC{step}-{step}_log.txt](https://github.com/user-attachments/files/16487500/NC.step.-.step._log.txt)

**Comment by f-brinkmann** [comment]
sorry for the delay - I did not read this during summer vacation. Unfortunetely we don't have the time to support issues on windows and with the inofficial Mesh2HRTF tutorials. I leave thin open for a while in case anyone from the community finds time to jump in...

**Comment by Pishisara** [comment]
Thank you for your response. It seems like no one is going to help me. I downloaded the mesh from this website and even tried it on a computer with 64GB of RAM. I don't get any error messages to understand where the problem is, and it just stops when it reaches the first 6 of each file.
