### ISSUE TITLE
dont have Apple/3D scanner

### ISSUE THREAD

**Issue by TheBestKmanEver** [Any2HRTF/Mesh2HRTF#140]
though i do have a good camera on my android phone... am i able to use this without needing to purchase additional stuff?? does a short video clip of the front to side of my head work???? i am anti apple and will never have an Apple product. i wont be able to afford anything for atleast a few years....

**Comment by f-brinkmann** [comment]
You could create a mesh using photogrammetry but it won't be of sufficient quality most likely...

**Comment by TheBestKmanEver** [comment]
yea i have no idea how to do this, meaning this application is completely useless to anyone that doesnt have Apple or a 3D scanner/lots of money
