### ISSUE TITLE
No idea what im doing... EDIT

### ISSUE THREAD

**Issue by TheBestKmanEver** [Any2HRTF/Mesh2HRTF#148]
[H13_3DScan.zip](https://github.com/user-attachments/files/17782564/H13_3DScan.zip)
i have an obj file from https://www.york.ac.uk/sadie-project/database.html and im just wanting it to be converted into a .sofa so i can use 'makemhr' via openal

yes i am aware they have the .sofa files available but openal cant use much of its layout

the Manual isnt helping me and blender just does not want to work.

**Comment by f-brinkmann** [comment]
I'm sorry that question is a little vague to support. Please go through the online documentation tutorials first: https://github.com/Any2HRTF/Mesh2HRTF/wiki/Mesh2HRTF-1.x
