### ISSUE TITLE
NumCalc throws error but doesn't stop execution

### ISSUE THREAD

**Issue by germknoedlspeck** [Any2HRTF/Mesh2HRTF#21]
When NC.inp is not written successfully (because, e.g., Blender is closed too early), NumCalc writes in the .out files "Error: cannot parse input file" but does not stop the execution, resulting in GB of output files if the programme call is not terminated early on.

**Comment by germknoedlspeck** [comment]
The NC*.out file(s) all contain the same three lines:

Start time
>> GENERAL PARAMETERS <<
3D analysis

and the logfiles contain

istart= 0 iend = 0
---------- NumCalc started DD/MM/YYYY HH:MM:SS ----------
Running on:    machine_name
3D analysis
Job title: Head-Related Transfer Functions

Error parsing the input file
Error parsing the input file
Error parsing the input file
Error parsing the input file
Error parsing the input file
Error parsing the input file

(this line goes on and on)

**Comment by schaastrommla** [comment]
Fixed
