### ISSUE TITLE
Link to "3d_Model_uniform.blend" does not work on Wiki.

### ISSUE THREAD

**Issue by SymphonX** [Any2HRTF/Mesh2HRTF#22]
See Wiki guide: https://sourceforge.net/p/mesh2hrtf/wiki/Installation_2/

The download link for the example file "3d_Model_uniform.blend" does not resolve [](https://sourceforge.net/p/mesh2hrtf/wiki/Tutorials/attachment/3d_Model_uniform.blend)

Could you update the guide with a working download? 

Thanks.

**Comment by SDX-LV** [comment]
Thank you for reporting - the link broke due to renaming of some Wiki pages.
Now it is fixed. (I can't close the issue)
