### ISSUE TITLE
NumCalc Manager does not run on Apple Silicon due to soundfilelib incompatibility. 

### ISSUE THREAD

**Issue by SymphonX** [Any2HRTF/Mesh2HRTF#23]
As the title suggests. NumCalc manager won't run on Apple Silicon CPUs due to an issue with the libsndfile dylib (or the python package). 

See: https://github.com/bastibe/python-soundfile/issues/310

Please point to this information in the guide as there currently appears to be no way to run the manager on the affected systems. Let's hope an update to python-soundfile will be released soon. 

Thanks.

**Comment by f-brinkmann** [comment]
How is this related to Mesh2HRTF and numcalc_manager? We do not you libsndfile. See requirements:
https://github.com/Any2HRTF/Mesh2HRTF/blob/develop/setup.py

Best, Fabian

**Comment by SymphonX** [comment]
BTW, according to my understanding pyfar, which is used in the project, uses soundfile, hence the error. This line made me suspicious: 

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyfar/io/io.py", line 17, in <module>
    import soundfile

Am I correct? Not the most savvy python user here, so forgive my ignorance ;-).

**Comment by f-brinkmann** [comment]
Thanks for clarifying - that makes sense. The next release seems to be close:
https://github.com/bastibe/python-soundfile/issues/325

We could also make soundfile optional for pyfar, but that might take longer than waiting for the new soundfile release.

**Comment by f-brinkmann** [comment]
@SymphonX the work on the new soundfile release seems to take longer than I hoped. We prepared a new relase where soundfile is optional: https://github.com/pyfar/pyfar/pull/334

**Comment by mberz** [comment]
You can also try installing libsndfile from conda-forge. At least the miniforge version does support arm64.

**Comment by SymphonX** [comment]
> Can you check if that works for you?

Thanks! I will check but it might take a week or so as I'm currently out of office. Looking forward testing this on the M1 Ultra!

**Comment by mberz** [comment]
The most recent version of pyfar (0.4.3) also includes a workaround for broken soundfile Imports due to m1 incompatibilities, beware though that reading and writing *.wav files won't work in this case.
