### ISSUE TITLE
Output2HRTF.py references wrong module.

### ISSUE THREAD

**Issue by SymphonX** [Any2HRTF/Mesh2HRTF#24]
The Output2HRTF.py script references a module titled 'Output2HRTF_Main' whereas in fact it should be 'output_to_hrtf'. 

Using the script in its current state will lead to termination of the post-processing. An example traceback is quoted below.

Solution: 
In line 36 of Output2HRTF.py script replace 'm2h.Output2HRTF_Main' with 'm2h.output_to_hrtf', as it is originally defined in Output2HRTF/Python/output_to_hrtf.py (line 15).

Pew ... took me a while to figure that one out ... 

THANKS!
-------------------------------------------
Traceback (most recent call last):
  File "C:\mesh2hrtf-tools\Finalize_HRTF_simulation\myHRTF_project_L\Output2HRTF.py", line 36, in <module>
    m2h.Output2HRTF_Main(Mesh2HRTF_version, sourceType,
AttributeError: module 'mesh2hrtf' has no attribute 'Output2HRTF_Main'. Did you mean: 'Output2HRTF'?
Traceback (most recent call last):
  File "C:\mesh2hrtf-tools\Finalize_HRTF_simulation\finalize_hrtf_simulation.py", line 448, in <module>
    subprocess.run(["python", "Output2HRTF.py"], cwd=Path1, check=True)  # run the normal Mesh2HRTF post-processing
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'Output2HRTF.py']' returned non-zero exit status 1.

**Comment by f-brinkmann** [comment]
Hi,

might it be that you are using an `Output2HRTF.py` that was generated a little while ago? `Output2HRTF_main` used to be the name of the function, but it was changes to `output_to_hrtf`. This is written in line 1020 of `exportMesh2HRTF.py` where it seems to be correct: `"m2h.output_to_hrtf(Mesh2HRTF_version, sourceType [...]"`. The problem should not happen if you export the project again.

Best, Fabian

**Comment by f-brinkmann** [comment]
ps. Or it might be that you need to remove and re-install the Blender export Add-On.
