### ISSUE TITLE
Road to Mesh2HRTF 1.0

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#25]
Mesh2HRTF can be released after these steps. The release is prepared in the branch `release/1.0` if possible make separate branches for the tasks and merge them into `release/1.0` once a task is completed.

**Code**
- [x] C1. Move *Pre-Processing* back to main repository, will be named *tools* (FB) 
- [x] C2. Rename `Mesh2HRTF/mesh2hrtf` to `Mesh2HRTF/core` (see below)
- [x] C3. Move `docs` to `readthedocs` in case we will have different documentations in the future
- [x] C4. Consistent names of functions across programming languages (FB)
- [x] C5. Distribute python functions across folders and make submodules accordingly, e.g., `m2h.core`
- [x] C6. Separate sources and binary in `Mesh2HRTF/mesh2hrtf/NumCalc` (WK)
- [x] C7. Write project parameter to json file and read parameters in `output2hrtf` (FB)
- [x] C8. Update Contributors (PM)
- [x] C9. Delete releases folder after D2 (remains in master until new release) (FB)
- [x] C10. Update mentions of sourceforge to github
- [x] C11. Update to final names

**Documentation**
- [x] D1. Remove project from SourceForge (FB)
- [x] D2. Add releases of Mesh2HRTF 0.x to Github again (FB)
- [x] D3. Move Wiki to GitHub (FB)
- [x] D4. Register Mesh2HRTF.org (PM)
- [x] D5. Update to final names

**Publication**
- [x] P1. Add *define materials*  and *define evaluation grid* to Fig. 1 and Section 1 (FB)
- [x] P2. Add section names to Fig. 1, e.g., *Mesh Preparation (Sec. 1)* (FB)
- [x] Update publication for changes

**Release**
- [x] R1. Merge everything in the master
- [x] R2. tag and release 1.0
- [x] R3. configure readthedocs for the master branch
- [x] R4. On the wiki main page, mention that the latest release is on the master branch
- [x] R5. Save project from tutorials on homepage for download.
- [x] R6. Update the readme on GitHub
- [x] R7. Add DOI of new publication to readme

**mesh2hrtf.org**
- [x] Add a reference of our paper when published in the **About Mesh2HRTF** section
- [x] Update the license information
- [x] Update the articles that should be cited when using Mesh2HRTF
- [x] Update list of publications that used Mesh2HRTF (we could also list third party publications, if we wanted to: https://scholar.google.com/scholar?start=0&hl=de&as_sdt=2005&sciodt=0,5&cites=2498946778044165472&scipsc=)
- [x] In the **Support** section, delete the **Help me!** part.

**Comment by f-brinkmann** [comment]
@germknoedlspeck @petibub this is my suggestion for C7 - consistent names of functions across programming languages. I had three rules for the names

- Use lower case letters (because upper case letters are usually reserved for classes in Python)
- Use verbose functions names that reflect what the function does
- Don't do unnecessary changes to the familiar names of the Matlab functions and use consistent terms.

Note that I already started C7, which means that we won't have `Output2HRTF` and `Output2VTK` files in the project folders anymore.

I will make the changes, once we agreed on the names.

| Matlab | Python | Final | Location |
| --- | --- | --- | --- |
| Output2HRTF_main | output_to_hrtf | output2hrtf | Output2HRTF |
| . | reference_hrtf | reference_hrtf | Output2HRTF |
| . | compute_hrir | compute_hrirs | Output2HRTF |
| Output2HRTF_RunAll | outputs_to_hrtfs | outputs2hrtfs | Output2HRTF |
|Output2HRTF_RunAll | remove_outputs | remove_outputs | Output2HRTF |
| Output2HRTF_ReadComputationTime | project_report | output_report | Output2HRTF |
| (not implemented) | inspect_sofa_files | plot_output | Output2HRTF |
| finalizeHRTFsimulation | merge_sofa_files | merge_output | Output2HRTF |
| (not implemented) | num_alc_manager | num_alc_manager | NumCalc |
| (not implemented) | run_numcalc_manager | run_numcalc_manager (script) | NumCalc |
| getMesh2HRTFevalGrid | read_evaluation_grid | read_evaluation_grid | Tools/EvaluationGrids |
| writeMesh2HRTFevalGrid |  write_evaluation_grid | write_evaluation_grid | Tools/EvaluationGrids |
| writeBoundaryCondition | write_boundary_condition | write_material | Tools/Materials |
| EvalToolsExport2VTK, ncdata2vtk | export_to_vtk | output2vtk | Tools/Visualization |

**Comment by petibub** [comment]
Thanks, Fabian! It would be good to have the same function names in Python and Matlab. Can we achieve that?

**Comment by f-brinkmann** [comment]
Yes, my suggestions for new names are in the column *Final*. Sorry, that was maybe not clear...

**Comment by f-brinkmann** [comment]
@petibub @germknoedlspeck I will start with Tasks C4 and C5 soon. Any objections against the suggested function names in the table above (column *Final*)

**Comment by SDX-LV** [comment]
Hi, I am now partially back. regarding "Check on Sergejs, if he wants to move his part as well (could help with that)."

What exactly is the plan with Wiki? Will the SourceForge site be completely discarded? It seems like a lot of stress to move Wiki at the same time as v1.0 release has so many other changes and documentation needs to be updated just to keep up. I think SourceForge works just fine for documentation/Wiki, but if everything is moved, we could manually move also the Basic tutorial for the same reasons as the rest.

Note that I don't have access to edit Wiki on GitHub.

Looking at all the changes proposed here, I am missing a release of the code that corresponds to the fully functional version from around 2022-05.

**Comment by f-brinkmann** [comment]
@SDX-LV Yes the idea is to completely move away from sourceforge to make things less confusing. If you want to, we could share the work. I move the basic tutorials and you update them later.

Regarding the release, we could have done that, but we had backwards incompatible changes after may, which would have resulted in Mesh2HRTF v2.0.0 with the current release. I wanted to avoid that. One way would be to refer to a certain commit that can be checked out.

**Comment by SDX-LV** [comment]
OK, I will move the Basic tutorials myself. It should not be too complicated. 
The full beginner tutorial update will be done after v1.0 release, when the code is stable and ready for testing/use.

**Comment by SDX-LV** [comment]
BTW, I finished the move of all Basic tutorials to GitHub.  From my perspective the original Sourceforge Wiki no longer contains any precious content.

Note that there are many older pages there that may not have an equivalent on GitHub, including all the v0.4 documentation.

**Comment by f-brinkmann** [comment]
Thanks for the effort @SDX-LV. I hope I ported all essential stuff also for the 0.4/5 documentation. We initially created a new v1.0 page for each existing page of the wiki, however, most v1.0 pages are still valid for v0.4 (evaluation grid, object meshes, NC.inp files, basic NumCalc usage) and are linked from the legacy documentation. I just checked again and added the old pages for most common errors, mesh2hrtf installation, and the Open Flipper mesh grading plugin

**Comment by petibub** [comment]
> Yes, my suggestions for new names are in the column _Final_. Sorry, that was maybe not clear...

The names sound good, but I have some questions: 
- why do we separate words in some functions with "_" and something we don't? Compare compute_hrirs vs outputs2hrtfs. 
- why do we have sometimes singular (e.g., write_material) and sometimes plural (e.g., compute_hrirs). Both examples compute a plurality of data. 
- having the same main words with singular and plural is confusing. Compare output2hrtf vs outputs2hrtfs. 
- num_alc_manager should be num_calc_manager, I guess

Can we still adapt the names to avoid those problems?

**Comment by petibub** [comment]
> Move Pre-Processing back to main repository, will be named tools (FB)

Thanks for moving. I have renamed that directory "Mesh2Input" in order to have a consistent structure of the directories (Mesh2Input, NumCalc, Output2HRTF). 

Also, in Mesh2Input I have renamed the directories to be more consistent: EvaluationGrids, Materials, Meshes. The file for the interaction with Blender is now in the directory "Blender". 

Can you adapt the remaining parts of the code to work with this new directory? If you agree to my changes, of course :-)

**Comment by petibub** [comment]
> * C3. Move `docs` to `readthedocs` in case we will have different documentations in the future.
> > moved to docs_python instead of readthedocs. This way we could have docs_matlab later.

I renamed back to "docs" just because docs_python is misleading (no other docs_xxx is available yet). If we'll provide other docs, we'll integrate into "docs" because from the user's perspective, there should be just one documentation. I also modified the .yml file accordingly, could you check if readthedocs still works correctly?

**Comment by f-brinkmann** [comment]
It's not too late for such changes, but they would require updating the entire Wiki, which contain 36 pages at the Moment. I can find time for changing the code and paper but not the Wiki. I thus moved the renamed folders to the branch https://github.com/Any2HRTF/Mesh2HRTF/tree/release/refactor and reverted them in https://github.com/Any2HRTF/Mesh2HRTF/tree/release/1.0. My only restriction for the function names is that they should not have upper case letters. Anything else is fine for me, but also requires updating the wiki.

**Comment by petibub** [comment]
By reverting, the problems I have raised are back again. Especially the naming of the directories within what is called now "Tools" does not follow a clear pattern. 

I understand that the wiki updates will take some effort. But this could be done later, after submitting the manuscript to the publisher. The manuscript will live for decades, the wiki can be updated as soon as we find somebody willing to do so - anytime.

**Comment by f-brinkmann** [comment]
It's easy and quick to bring those changes back. How about collecting changes here and then I will bring them back en block (only changing folder or file names breaks testing and the python package). I would suggest not to wait too long with updating the Wiki, since people might get confused and will pose more issues.

Anyone - please add or adapt your suggestions below. Can we say that names are final if there are no comments left?

**Folders**
| Current | Final | Comment |
| --- | --- | --- |
| Tools | Mesh2Input |
| Tools/BlenderExport | Blender | FB: I prefer BlenderExport. It is more specific, and we have more Blender AddOns (MaterialAssignment and Center Mesh) in other folders |
| Tools/MeshManipulation | Meshes |

**Functions and Scripts**
| Current | Final | Cooments |
| --- | --- | --- |
| output2hrtf |  |
| reference_hrtf |  |
| compute_hrirs |  |
| outputs2hrtfs |  |
| outputs2trash |  |
| write_output_report |  |
| inspect_sofa_files | |
| merge_sofa_files |  |
| numcalc_manager |  |
| run_numcalc_manager (script) |  |
| read_evaluation_grid |  |
| write_evaluation_grid |  |
| write_material |  |
| output2vtk ||

**Comment by petibub** [comment]
Fabian, brauchst du underscores in den Namen?

**Comment by petibub** [comment]
für Folders habe ich gleich dein Kommentar editiert...

**Comment by petibub** [comment]
Ich habe nun auch Vorschläge für "Functions and Scripts" gemacht - alle folgen der Struktur "verb_objekt", bis auf output2hrtf, was somit heraussticht.

**Comment by f-brinkmann** [comment]
Thanks saw the changes and responded - we do not need underscores in the names

**Comment by petibub** [comment]
I responded and cleaned up where consensus. Could you have a look (my responses in bold).

**Comment by f-brinkmann** [comment]
I agreed to all comments and finalized the table

**Comment by petibub** [comment]
Perfect. I just modified the description to have the same format in all rows.

**Comment by f-brinkmann** [comment]
@petibub @germknoedlspeck: all changes are done including the wiki and paper and the latest stable version is back in the develop branch. I did a quick check of the Matlab output2hrtf version as well. Last thing to decide: should it be Mesh2Input/Meshes or Mesh2Input/MeshManipulation. Kathi noted that the first might be misleading, because we are not storing meshes but tools for mesh manipulation.

**Comment by petibub** [comment]
Thanks to Kathi for catching that. "Meshes" really sounds as if we're storing meshes there - while we actually do not. So I agree for the need to resolve that problem. Let my try: 

"MeshManipulation" would be rather inconsistent because we also manipulate the evaluation grids and materials in the folders called "EvaluationGrids" and "Materials", respectively. So, why "Manipulations" in meshes, why not elsewhere as well? 

I think that the problem started already a decade as we mixed data with algorithms in the same directory: 
- "Materials" contains materials (=data) and algorithms for their manipulation
- "EvaluationGrids" contains grids (=data) and algorithms for their manipulation
- "Meshes" contains algorithms only. No data. 

This was (is) inconsistent, we did not think that well through. Now, with 1.x we could resolve that and and I see three potential solutions to this problem: 
1. Separate data and algorithms. Let's create a new directory in Mesh2HRTF root folder called, e.g., Data and store the materials and grids (and potential future data) there. Then the three folders within Mesh2Input could be called "EvaluationGrid", "Material", "Mesh" and would contain algorithms only(!). Note that would correspond to NumCalc and Output2HRTF in which we do store algorithms only. 
2. Put "Manipulation" in all three folders: "EvaluationGridManipulation", "MaterialManipulation", "MeshManipulation". Weird, redundant, but hey, consistent and thus a way to go. 
3. Use singular arguing that this removes the focus from data a bit. Thus, we'd have "EvaluationGrid", "Material", "Mesh". In the first two, we store data, in the third, the user can store data, if desired. In the doc, we could explain, that in these folders, we store both both data and algorithms, depending on the particular needs. 

What do you think?

BTW, I vote for #3 as the best compromise. (#1 is even better but much more effort and we want to release soon, I guess)

**Comment by f-brinkmann** [comment]
I also vote for 3.

1 would also be possible, but I think having the 'data' folder at top-level would not be optimal, because so far the only relevant top-level folder for the users is mesh2hrtf. Moving the potential 'data' folder to 'mesh2hrtf/data' would require a 'mesh2hrtf/algorithms' folder to be consistent - and that would mix everything up.

**Comment by f-brinkmann** [comment]
I just wanted to make the changes and recognized that we also have the 'EvaluationGrids' folder in the project folder generated upon Blender export. Having the folders with and without the plural s might also be confusing. How about option

4. Leave everything as it is but as in 3: explain, that in these folders, we store both both data and algorithms, depending on the particular needs.

**Comment by germknoedlspeck** [comment]
If we separated algorithm and data, we could also introduce "code" (or "core", which I'd prefer) and "data" in root. Would that be a good compromise?

**Comment by petibub** [comment]
I this case, if we need plural, then let's leave everything in plural and explain that in "Meshes" we (currently) do not store meshes but only algorithms. We could go then by "EvaluationGrids", "Materials", "Meshes". 
Actually, we even could create "Data" in "Meshes" and store a mesh as an example - a reference example that works with Mesh2HRTFs and helps users to start with a working project. What about that?

**Comment by f-brinkmann** [comment]
I'm in favor of @petibub suggestion. @germknoedlspeck , we wanted to rename 'mesh2hrtf' to 'core' but that was not possible due to the python package.

Which mesh should we use? The uniform or graded mesh from the online tutorials or the left ear graded mesh from the paper?

**Comment by germknoedlspeck** [comment]
> Actually, we even could create "Data" in "Meshes" and store a mesh as an example - a reference example that works with Mesh2HRTFs and helps users to start with a working project. What about that?

In that case, we would create an extra step (i.e., an additional subfolder) getting to an example mesh.

I'm not sure about the example mesh. My thoughts are: if we include a mesh, we could also include the resulting SOFA files (both HRTF and HRIR), and an example Mesh2HRTF project folder, and a demo of the whole project. If we include an example mesh, I would also prefer one that has been used in the online tutorial, so people can reproduce results.

**Comment by f-brinkmann** [comment]
although it would be nice to store the entire project and results, I think that would take too much space - a couple of hundreds MB at least.

**Comment by germknoedlspeck** [comment]
> although it would be nice to store the entire project and results, I think that would take too much space - a couple of hundreds MB at least.

exactly my point :)

**Comment by germknoedlspeck** [comment]
Maybe we can store an example project on the project homepage instead?

**Comment by f-brinkmann** [comment]
Good idea - I added it to the list above. We could still do that after submitting the paper.

**Comment by germknoedlspeck** [comment]
Excellent, thank you 👍 

Back to the Code/Data problem. We need the folder EvaluationGrids so Mesh2Input knows where to look for the evaluation grid(s) the user wants to use. I just had a look at the current folder structure as is in the develop branch (i.e., there is the folder EvaluationGrids with all functions to use, and another folder "data" for the evaluation grids), and I actually like it that way 😄

**Comment by f-brinkmann** [comment]
I added the tutorials to the repository, see #46 for more information
