### ISSUE TITLE
Solution for running NumCalc with higher sample rate

### ISSUE THREAD

**Issue by eoolatm** [Any2HRTF/Mesh2HRTF#26]
Hello, 
I've been looking for information in the documentation but haven't found what I'm looking for. Feel free to just direct me to a relevant source if there is one. Otherwise I am happy to receive guidance on this issue:

I am trying to run NumCalc with sample rate 48k Hz so (max_frequency=24k Hz) on a head mesh from the CHEDAR database (pre-processed according to recommendations). I see that the maximum frequency calculated by NumCalc is around 18k Hz, and so the calculations for frequencies >~ 20k Hz fail to converge.

My question is if there is any way to process the mesh so that the maximum frequency can be higher in the NumCalc calculations? Or if there are other parameters to tweak so that a higher sample rate can be achieved?

Best regards, Mattias

**Comment by f-brinkmann** [comment]
Hi Mattias,

a 'bad' mesh is most often the cause for non-convergence issues. Possible workarounds are to play with the re-meshing (I would to that first) or to try a slighty different configuration of NumCalc's clustering algorithm as noted here: https://sourceforge.net/p/mesh2hrtf/wiki/Most%20common%20errors/

Best, Fabian

**Comment by f-brinkmann** [comment]
closed due to inactivity - feel free to re-open...
