### ISSUE TITLE
small change needed

### ISSUE THREAD

**Issue by SDX-LV** [Any2HRTF/Mesh2HRTF#3]
Hi, I noticed that creation of multi_SamplingRate_HRIRs using "finalize_HRTF_simulation.py" no longer works because of the new code that parses every "NC*.out" file and writes stats.

I tested the fix which is to add into "output_to_hrtf.py" after line 555 these 3 lines:
```
                    if num_frequencies < step:
                        # special case if the "output_to_hrtf" is called to process not all frequency steps.
                        out = np.append(out, -np.ones((1, 11, num_sources)), axis=0)
```

so that the code looks like this:

```
                # find frequency step
                idx = re.search(r'Step \d+,', line)
                if idx:
                    step = int(line[idx.start()+5:idx.end()-1])
                    if num_frequencies < step:
                        # special case if the "output_to_hrtf" is called to process not all frequency steps.
                        out = np.append(out, -np.ones((1, 11, num_sources)), axis=0)

                # write number of input file (replaced by string later)
```

This is much more elegant fix than making complex workarounds from the outside (within "finalize_HRTF_simulation.py")

The appending one line at a time is not very efficient, but it only happens when executed by "finalize_HRTF_simulation.py" and we are doing this for quite small array usually just 26 times - negligible performance impact.

Thanks

**Comment by f-brinkmann** [comment]
Hi Sergejs, I'm not sure if I understand the context. In which cases does `num_frequencies < step` occur? I think the above suggestion would only work if `steps` exceeds `num_frequencies` by exactly one. Otherwise the array would be too small. If we do this, we should also add the correct default values of or columns 0, 3, and 4 (lines 499 ff.)

As an alternative solution: In case you know the value of  `num_frequencies`, you could pass it during the call to `output_to_hrtf`

Best, Fabian

**Comment by SDX-LV** [comment]
Sorry, I missed your reply due to being bombarded by dozens of Mesh2HRTF wiki and code change commits :)

The proposed change works, because it adds an extra "row" one by one inside a loop - I already tested the code.
Note that this command will do absolutely nothing in all other cases (because you will not have `num_frequencies < step` condition).

So it re-enables the full functionality of [finalize_HRTF_simulation.py](https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/Finalize_HRTF_simulation/finalize_HRTF_simulation.py) and does no harm. There may be more elegant way to use the new `output_to_hrtf`, but that would require a major re-write of `finalize_HRTF_simulation.py`. Currently I just change the `Info.txt` (after making a backup) and re-run the `Output2HRTF.py` to get the HRIRs at lower sampling rates.

You will see it in action in the part 8 of the video tutorial, soon :)

**Comment by f-brinkmann** [comment]
Ok I see. We can do that but I would prefer the clean solution. Would you be open to change something in finalize_HRTF_simulation.py? I could take a look if you point me to the lines. It might be easy to read the existing HRTF sofa files, remove or add a couple of frequencies and than re-run `reference_hrtf` and `compute_hrir` again.

**Comment by f-brinkmann** [comment]
The new feature is now merged into develop
