### ISSUE TITLE
NumCalc CPU Core problem

### ISSUE THREAD

**Issue by WZS666** [Any2HRTF/Mesh2HRTF#37]
Hello team,
Thanks for sure this wonderful project.
As I saw at Advanced Numcalc tips
![image](https://user-images.githubusercontent.com/39181744/181442264-2a32871e-beea-479c-9f9c-1fedfb29bdc0.png)
Numcalc can only use single threaded. So CPU core only usage low 10%.
it's possibles to make it to the multi-thread? or it had some limit so we can only use multi-process. Just curious.

Thanks a lot.

**Comment by f-brinkmann** [comment]
Hi,

I'm not sure if it would be possible @schaastrommla might know this. However, running eight NumCalc instances in parallel usually uses up the CPU on my machines already. The easiest way for parallelization is the 'numcalc_manager':
https://github.com/Any2HRTF/Mesh2HRTF/wiki/NumCalc

Best, Fabian

**Comment by f-brinkmann** [comment]
closed due to inactivity
