### ISSUE TITLE
Provide inspect_sofa_files for Matlab

### ISSUE THREAD

**Issue by petibub** [Any2HRTF/Mesh2HRTF#38]
Implement inspect_sofa_files (available for Python) for Matlab. This is probably rather easy when SOFAplotHRTFs can be accessed.

**Comment by germknoedlspeck** [comment]
Is this similar to including hrtf2dtf conversion in Mesh2HRTF? This functionality seems to be covered by using SOFAplotHRTF.

**Comment by f-brinkmann** [comment]
should we close this?

**Comment by germknoedlspeck** [comment]
I don't know what the benefit of this functionality would be, since the SOFAtoolbox has to be in the Matlab PATH anyway (since we create a SOFA file within output2hrtf).

@petibub was there a specific reason for opening this issue?

**Comment by f-brinkmann** [comment]
I added the hint to SOFAtoolbox in https://github.com/Any2HRTF/Mesh2HRTF/wiki/Mesh2HRTF_API
