### ISSUE TITLE
Output2HRTF: FileNotFoundError on MacOS

### ISSUE THREAD

**Issue by DenysVolkov** [Any2HRTF/Mesh2HRTF#41]
Hi guys! Trying to run though your amazing library using the [Unix_Tutorials](https://github.com/Any2HRTF/Mesh2HRTF/wiki/Unix_Tutorials) page on my Mac (Catalina 10.15.4) and facing an issue with the [Scattering from a rigid sphere](https://github.com/Any2HRTF/Mesh2HRTF/wiki/Unix_Tutorials#scattering-from-a-rigid-sphere) tutorial. 

UPD: I'm using Mesh2HRTF v. 1.0.0

Blender part works smooth, and NC works good as well, but when using NC output in Python i have the following error:
```
import mesh2hrtf as m2h
m2h.output2hrtf('rigid_sphere')

```
`FileNotFoundError: rigid_sphere/EvaluationGrids/.DS_Store/Nodes.txt not found.`

I don't really understand why it tries to look into the .DS_Store folder. Will be most appreciative for any thoughts about how to solve this, thanks a lot!

**Comment by f-brinkmann** [comment]
Hi Denys,

can you paste the complete error please - this might give us hints where to look.

Best, Fabian

**Comment by f-brinkmann** [comment]
I think I found the problem. DS_Store is a folder, and Mesh2HRTF assumes all folders to be evaluation grids. Inserting the line

`objects = [o for o in objects if not o.startswith('.')]`

after the line 156

`objects = os.listdir(folder)`

hopefully fixes the problem. If you let me know how it worked, I'll commit the fix later today. I will also look for similar expressions that could be problematic...

**Comment by DenysVolkov** [comment]
It solved previous problem, but another one appeared: 


```
runfile('/Users/denys.volkov/Documents/Mesh2HRTF/Tutorials/Rigid sphere/HRTF_export.py', wdir='/Users/denys.volkov/Documents/Vision/Mesh2HRTF/Tutorials/Rigid sphere')
Reloaded modules: mesh2hrtf.NumCalc, mesh2hrtf.NumCalc.manage_numcalc, mesh2hrtf.Output2HRTF, mesh2hrtf.Output2HRTF.inspect_sofa_files, mesh2hrtf.Output2HRTF.merge_sofa_files, mesh2hrtf.Output2HRTF.output2hrtf, mesh2hrtf.Output2HRTF.reference_hrtfs, mesh2hrtf.Output2HRTF.compute_hrirs, mesh2hrtf.Output2HRTF.export_vtk, mesh2hrtf.Output2HRTF.process_multiple_outputs2hrtf, mesh2hrtf.Output2HRTF.remove_outputs, mesh2hrtf.Output2HRTF.read_ram_estimates, mesh2hrtf.Output2HRTF.write_output_report, mesh2hrtf.Mesh2Input, mesh2hrtf.Mesh2Input.EvaluationGrids, mesh2hrtf.Mesh2Input.EvaluationGrids.read_evaluation_grid, mesh2hrtf.Mesh2Input.EvaluationGrids.write_evaluation_grid, mesh2hrtf.Mesh2Input.Materials, mesh2hrtf.Mesh2Input.Materials.write_material, mesh2hrtf

 Writing the project report ...

 Loading the EvaluationGrids ...

Loading data for the evaluation grids ...

 Loading pEvalGrid data ...

    Source 1 ...
Traceback (most recent call last):

  File "/Users/denys.volkov/Documents/Mesh2HRTF/Tutorials/Rigid sphere/HRTF_export.py", line 4, in <module>
    m2h.output2hrtf('rigid_sphere')

  File "/Users/denys.volkov/Documents/Mesh2HRTF/mesh2hrtf/Output2HRTF/output2hrtf.py", line 77, in output2hrtf
    pressure, _ = _read_numcalc_data(

  File "/Users/denys.volkov/Documents/Mesh2HRTF/mesh2hrtf/Output2HRTF/output2hrtf.py", line 198, in _read_numcalc_data
    tmpPressure, indices = _output_to_hrtf_load(

  File "/Users/denys.volkov/Documents/Mesh2HRTF/mesh2hrtf/Output2HRTF/output2hrtf.py", line 354, in _output_to_hrtf_load
    tmpData.append(complex(float(li[1]), float(li[2])))

IndexError: list index out of range
```

**Comment by f-brinkmann** [comment]
That one is more peculiar - can you upload the project some where, so I could try to reproduce it?

**Comment by DenysVolkov** [comment]
Absolutely! Here is the link to my drive: https://drive.google.com/file/d/168NVfsNN4H97hJ3eNFdqnfcKrQWEuQ9T/view?usp=sharing

Let me know if you can access it or need any additional information.

**Comment by f-brinkmann** [comment]
The files in Rigid sphere/NumCalc/source_1/be.out/be.11 contain and empty line after the first line. If you remove that everything should be fine.

I've never seen that happen. Did you do any manual changes that might have caused that?

**Comment by DenysVolkov** [comment]
Thanks for pinpointing that! I looked into other folder and there've been an additional empty line also in the folders b.12 and b.13. But only in these three, the ones below and above are good. After removing the empty lines i've got the .sofa file generated. 

I don't think i've done anything specific to it, was trying to follow the tutorial. I'll try to run through it one more time from scratch and report the outcome a bit later.

Thanks a lot again!

**Comment by f-brinkmann** [comment]
I committed a little fix for the problem. Can you test if the blank lines still occur if you change the text in the file VERSION from

'Mesh2HRTF 1.0.0-dev'

to

'Mesh2HRTF 1.0.0'

**Comment by f-brinkmann** [comment]
Thanks for sticking to it. I think that is unrelated. Can you open a new issue and upload the project to be checked? It's a good beta testing before the release...

**Comment by DenysVolkov** [comment]
Sure, will do! Thank you very much for digging into this!
