### ISSUE TITLE
Version string causes emtpy lines in output-files

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#43]
The current Version string is '1.0.0-dev' which seems to cause empty lines in the NumCalc output files in some cases -see #41.

We could
- fix this in NumCalc
- return to plain version strings, e.g., '1.0.0'

I would vote for the plain strings because that makes comparing versions easier and we would not have to test if the verbose version strings cause problems elsewhere.

@petibub, @schaastrommla, @germknoedlspeck what do you think?

**Comment by petibub** [comment]
The "-dev" postfix helps to distinguish the released version from the developer version. For example, just before the release of 1.0.0, we'd change 1.0.0-dev to 1.0.0, create the release, and then bump the version to, say, 1.0.1-dev. 

Note that "1.0.0" is a string. 
If NumCalc has problems handling a string "1.0.0-dev", but it can handle "1.0.0", it would be good to fix NumCalc. 

But I'm happy with any other workflow providing the described functionality.

**Comment by f-brinkmann** [comment]
I'm not sure if there is one right way. In pyfar all code on all branches has the same version and its only bumped for a new release. I think the idea behind that is that the version should (must) tell what exact state of the code was used. This does not work on the develop branch unless we change the version for every commit. If you want to use code from develop in a reproducible way, the commit tag is probably the way to got.

I prefer that over bumping the version on develop after a release. And for simplicity, I would prefer the version string without the dev suffix.

**Comment by petibub** [comment]
All I suggest is to be able to distinguish between the release versions and the developer code versions (before and after the release). As I'm not bound to "-dev", I don't understand, when you change now the developer code to "1.0.0", how do you distinguish after the release of "1.0.0" the current code from the released code? Or do you propose to change to "0.9.9999"? People also use "1.0.0-alpha" or "1.0.0-pre1", "1.0.0-pre2", "1.0.0-pre3", etc, but than we again have letters in the string...

After the release, we could bump the version to "1.0.1" presuming that the next release will be 1.0.1. 

Of course, to be on a perfect side, each commit could be bumped. For me, it would be too much, see also: https://betterprogramming.pub/how-to-version-your-code-in-2020-60bdd221278b

And for clarity: if NumCalc can go with the string "1.0.0" but cannot with the string "1.0.0-dev", it's a bug in NumCalc.

**Comment by f-brinkmann** [comment]
The release is contained in the master and on the release page - I would say that how to distinguish. The cases of '1.0.0-alpha' probably also mark a release and not code in a branch. Since the master branch is the default, it's not very likely that someone accidentally downloads or clones the develop code. I would suggest to only bump versions upon releases.

Anyhow, fixing NumCalc to handle those strings is a good idea in any case.

**Comment by petibub** [comment]
I'll ask Wolfgang to check in NumCalc why we have an error because of this...

**Comment by f-brinkmann** [comment]
I noted that NumCalc writes the project name after the version number. It might also be the project name that causes the behavior. We could remove any special characters from the project name or stop writing it to the output files.

**Comment by schaastrommla** [comment]
> And for clarity: if NumCalc can go with the string "1.0.0" but cannot
> with the string "1.0.0-dev", it's a bug in NumCalc.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
nope its a feature ;-)

this should be fixed now, as long as MESH2HRTF + version number is not
longer then 20 characters, we should be fine 
if not, i will need to reserve more space in the char-array, this has
been done old school

kreiza
-- 
Wolfgang Kreuzer
Austrian Academy of Sciences
Acoustics Research Institute
Wohllebengasse 12-14
1040 Vienna, Austria
Tel.: +43 1 51581-2518
Fax.: +43 1 51581-2530
***@***.***

**Comment by petibub** [comment]
Perfect, thanks! @f-brinkmann : should we close this issue or would you like to change the versioning system in addition to fixing this "feature" ;-) ?

**Comment by schaastrommla** [comment]
On Thu, 2022-08-18 at 00:42 -0700, Piotr Majdak wrote:
> Perfect, thanks! @f-brinkmann : should we close this issue or would
> you like to change the versioning system in addition to fixing this
> "feature" ;-) ?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
i replaced the char arrays of version number and title with strings, we
should be save now, with any version system

kreiza
-- 
Wolfgang Kreuzer
Austrian Academy of Sciences
Acoustics Research Institute
Wohllebengasse 12-14
1040 Vienna, Austria
Tel.: +43 1 51581-2518
Fax.: +43 1 51581-2530
***@***.***

**Comment by f-brinkmann** [comment]
great - let's close once the fix is committed

**Comment by schaastrommla** [comment]
On Thu, 2022-08-18 at 02:47 -0700, Fabian Brinkmann wrote:
> Closed #43 as completed.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>

question with respect to that topic:
we now have only the version number in the first line, which is cool
for downwards compatibility. Would it also be of help to put the title
of the project in this line, too? Would that mess up all the output
processing routines ?

kreiza
-- 
Wolfgang Kreuzer
Austrian Academy of Sciences
Acoustics Research Institute
Wohllebengasse 12-14
1040 Vienna, Austria
Tel.: +43 1 51581-2518
Fax.: +43 1 51581-2530
***@***.***

**Comment by f-brinkmann** [comment]
I think it potentially messes with the output routines and we already have the project name in the NC.inp and parameters.json files. So I am fine with keeping this as it is
