### ISSUE TITLE
Output2HRTF export error ( Mesh2HRTF v1.0.0, MacOS Catalina 10.15.4)

### ISSUE THREAD

**Issue by DenysVolkov** [Any2HRTF/Mesh2HRTF#45]
Hi guys! I was trying to follow the [Official Tutorials](https://github.com/Any2HRTF/Mesh2HRTF/issues/Unix_Tutorials) and faced a problem with exporting HRTF. Mainly, when i run:

```
import mesh2hrtf as m2h
m2h.output2hrtf('radiation')
```

I have the following error:

```
runfile('/Users/denys.volkov/Documents/Mesh2HRTF/Tutorials/radiation/hrtf_export.py', wdir='/Users/denys.volkov/Documents/Mesh2HRTF/Tutorials/radiation')

 Writing the project report ...

 Loading the EvaluationGrids ...

Loading data for the evaluation grids ...

 Loading pEvalGrid data ...

    Source 1 ...

Saving HRTFs for EvaluationGrid "Default" ...

Traceback (most recent call last):

  File "/Users/denys.volkov/Documents/Mesh2HRTF/Tutorials/radiation/hrtf_export.py", line 4, in <module>
    m2h.output2hrtf('radiation')

  File "/Users/denys.volkov/Documents/Mesh2HRTF/mesh2hrtf/Output2HRTF/output2hrtf.py", line 111, in output2hrtf
    sf.write_sofa(os.path.join(

  File "/Users/denys.volkov/opt/anaconda3/envs/mesh2hrtf/lib/python3.8/site-packages/sofar/sofar.py", line 1761, in write_sofa
    sofa.verify(version)

  File "/Users/denys.volkov/opt/anaconda3/envs/mesh2hrtf/lib/python3.8/site-packages/sofar/sofar.py", line 1015, in verify
    error_occurred, issues = self._verify_handle_issues(

  File "/Users/denys.volkov/opt/anaconda3/envs/mesh2hrtf/lib/python3.8/site-packages/sofar/sofar.py", line 1087, in _verify_handle_issues
    raise ValueError(error_msg)

ValueError: 
ERRORS
------
Detected variables of wrong shape:
- ReceiverPosition has shape (2, 3, 1) but must have (I=1, C=3), (R=1, C=3), (R=1, C=3, M=1850)

```
I tried it for both 'Default' and 'ARI' grids. You can find my project here: https://drive.google.com/file/d/1m7x4_HlmMOY23iSDtrYdXUnnjPalXLSP/view?usp=sharing

There are two NumCulc realisations under `Tutorials/radiation/radiation` and `Tutorials/radiation/radiation_ari`, I have the same error for both of them. 

I will be most appreciative if you could take a look at this issue. Thank you very mush in advance!

**Comment by f-brinkmann** [comment]
Hi and thanks for reporting. I think it is fixed now with the latest commit on develop. You can test by

- re-installing the updated mesh2input addon
- export the project
- copy the parameters.json to your existing folder
- run output2hrtf again

The problem was that the positions for the left and right ear were written to parameters.json (fields  sourceCenter and sourceArea). Using the update should write only one to parameters.json.

I'm preparing to include the tutorials in the testing on the branch https://github.com/Any2HRTF/Mesh2HRTF/tree/feature/add_and_test_tutorials

**Comment by DenysVolkov** [comment]
Great, seems to perfectly work now. Thank you very much!

**Comment by DenysVolkov** [comment]
Also, fell free to let me know if I can check something else before the release.

**Comment by f-brinkmann** [comment]
Great - I think running the tutorials and checking the documentation is a good test. If you find anything that was hard to understand or could be improved let us know, and I'll look over it.
