### ISSUE TITLE
NumCalcManager.py script required Info.txt file

### ISSUE THREAD

**Issue by DenysVolkov** [Any2HRTF/Mesh2HRTF#48]
Hello! 

I am now trying to go through the tutorials on Windows pc and using prebuilt mesh2hrft-tools. The current projects exported from Blender do not have Info.txt file, which is, i assume, now replaced by the parameters.json. Info.txt is required in the NumCalcManager.py script to be considered as mesh2hrtf project folder. Here is the error that i receive:

```
(mesh2hrtf) C:\Personal\Mesh\mesh2hrtf-tools>python NumCalcManager.py 
NumCalcManager started with StartPath = "C:\Personal\Mesh\mesh2hrtf-tools" 
ERROR - StartPath = "C:\Personal\Mesh\mesh2hrtf-tools" does not contain any Mesh2HRTF projects to run 
 Please make sure that "StartPath" variable is set correctly 
  -press Enter- to exit NumCalcManager. 
Traceback (most recent call last): 
  File "NumCalcManager.py", line 120, in <module> 
    raise Exception("not ok to continue") 
Exception: not ok to continue
```

I am not sure that this is a correct place for this issue, because mesh2hrft-tools is a different repo, but the windows tutorials here are pointing to it. Let me know if i should raise this issue elsewhere.

**Comment by f-brinkmann** [comment]
The Windows tools are in limbo and will be updated soon - they are currently not working with the latest Mesh2HRTF API. @SDX-LV can you update this issue, once you are done?

**Comment by SDX-LV** [comment]
Hi, I am starting work to update the tools to the newest version. There already exists a brand new num calc manager in the main repo that works with the new format. everything should be updated very soon.

**Comment by DenysVolkov** [comment]
Sounds great, guys, thanks you! Looking forward to try it out!

**Comment by SDX-LV** [comment]
in case you are in a hurry, there still is the legacy tutorial with matching Mesh2HRTF version that is tested to work well: https://sourceforge.net/p/mesh2hrtf-tools/wiki/Basic_HRTF_tutorial/  you just need to download https://github.com/SDX-LV/Mesh2HRTF_contributions/releases/download/v0.99/Mesh2HRTF_v2022-06.zip

Last night I ran into some issues, so I am not sure how quickly I can update the tutorials for the latest Develop branch. Your choice - either wait for the coming tutorial version or use the same version as in the video tutorials.

**Comment by DenysVolkov** [comment]
Alright, understood, thank you!

**Comment by SDX-LV** [comment]
For about a month all tutorials and files are up-to-date, so this issue should be fixed.

In case someone still uses earlier version with `info.txt`, then the legacy tutorial and code is also preserved: https://sourceforge.net/p/mesh2hrtf-tools/wiki/Basic_HRTF_tutorial/
