### ISSUE TITLE
merge_sofa_files.m saves only one parameters.json file to targetdir

### ISSUE THREAD

**Issue by germknoedlspeck** [Any2HRTF/Mesh2HRTF#53]
```
% copy parameters.json to targetdir
if isfile(fullfile(folder_names{1}, 'parameters.json'))
    copyfile(fullfile(folder_names{1}, 'parameters.json'), targetdir);
end
```

If a _targetdir_ is specified to save the merged SOFA files, only the parameters.json of the PATH of input 1 is copied. Both parameters.json files should be merged as well.

**Comment by germknoedlspeck** [comment]
@petibub is there a need to save a merged parameters.json file? As far as I am concerned, it's fine to keep only the parameters.json for the single sources (ears).

**Comment by germknoedlspeck** [comment]
For now, deleted the code snippet so no additional (incomplete) data is being copied unnecessarily.

**Comment by petibub** [comment]
I'm not sure if I understand this issue. But if your proposed solution makes you happy, I'm happy as well and close this issue...
