### ISSUE TITLE
HRIR.sofa object does not contain correct hrir data

### ISSUE THREAD

**Issue by germknoedlspeck** [Any2HRTF/Mesh2HRTF#54]
When using the latest develop version of output2hrtf.m, the time-domain data in the hrir.sofa object seems to save incorrect(ly saved/formatted) data.

This is the output when plotting 'EtcHorizontal' with the current output2hrtf.m version:
![hrir_new](https://user-images.githubusercontent.com/16223869/196476363-58f48356-0d86-41ba-97f8-3340fe7ee95f.png)

This is the output of an older Output2HRTF_Main.m version (before switching to the parameters.json implementation):
![hrir_old](https://user-images.githubusercontent.com/16223869/196476333-8ab9ba8b-8010-4f21-8659-79c216f98158.png)

@f-brinkmann: Does this just occur for the Matlab-side of output2hrtf or is this a problem in the python implementation, too?

**Comment by f-brinkmann** [comment]
Can you share the project and sofa file somehow?

**Comment by germknoedlspeck** [comment]
I'll send you a WeTransfer Link (because of size) via Email (because of data privacy)!

**Comment by f-brinkmann** [comment]
The data in the SOFA files looks fine to me - see below. I assume something is going wrong in the plotting routines. Did anything change in SOFAtoolbox?

```python
import mesh2hrtf as m2h

# plot with Mesh2HRTF (uses pyfar)
folder = "calculation_L"
m2h.inspect_sofa_files(folder, plot="3D")
```

![HRIR_ARI_3D](https://user-images.githubusercontent.com/58219902/196612149-b13ca583-aece-44ca-ae34-47ad08d612ff.jpeg)

```python
import pyfar as pf

# plot first channel directly with pyfar
sofa, *_ = pf.io.read_sofa(r"calculation_L\Output2HRTF\HRIR_ARI.sofa")
pf.plot.time_freq(sofa[0])
```


![Screenshot 2022-10-19 082116](https://user-images.githubusercontent.com/58219902/196612317-34c78048-98f3-453b-9e85-c2f02d3db5ee.png)

**Comment by germknoedlspeck** [comment]
Thank you for trying it out!

I'm still unsure the same kind of data is written to the SOFA files, because in the old version, real and imaginary part are between -13 and +15, in the new one around -4e-6 and +5e-6. Same goes for the IR data, in the old SOFA file, the amplitude is around +-3, and in the new file, it's around 0.0039(+-something e-6).

**Comment by germknoedlspeck** [comment]
You have to compare both folders (I sent you an old and new project folder of the same ear). I'm puzzled why the differences in amplitude are so large between the old and the new SOFA objects.

**Comment by germknoedlspeck** [comment]
> could it be that the old script calculated and saved the data in dB, maybe also including a normalisation to 20 µPa?

Or rather that the 0 Hz bin - now we deal with raw pressure - should be 2e-5 instead of 1 to yield 0 dB afterwards?

**Comment by germknoedlspeck** [comment]
@f-brinkmann I think I solved it.

We only add the 0 Hz bin to calculate the HRIR, and if this is anything but 0, we add a(n unwanted) DC component to the time signal.

I'll change it in the code asap!

**Comment by f-brinkmann** [comment]
I think https://github.com/Any2HRTF/Mesh2HRTF/commit/a2e8236d1b1384eb47b38ac5a48730ee6d2e90db does not fix the problem but adds another. The one is added to the transfer function, which means the HRTF does not have any effect at 0 Hz. It does not add a DC component. Think of a dirac pulse, that also with constant energy across the entire spectrum, including 0 Hz. Using zero adds a high-pass effect. I would suggest to revert this.

Stupid me deleted the we-transfer links. Can you re-send the E-Mail to me? I'll try to also have a closer look the next days.

**Comment by germknoedlspeck** [comment]
This is why we create two different SOFA Objects. I was talking about the HRIR-Object, the HRTF-Object is not affected by this. Also, we do not add 0 Hz for the HRTF-Object.

No worries, I'll resend you the links!

**Comment by f-brinkmann** [comment]
> could it be that the old script calculated and saved the data in dB, maybe also including a normalisation to 20 µPa?

As far as I remember, we never referenced to 20 micro Pa.

> This is why we create two different SOFA Objects. I was talking about the HRIR-Object, the HRTF-Object is not affected by this. Also, we do not add 0 Hz for the HRTF-Object.

Its indeed added to the HRTF, but its not safed/returned. After adding it, the inverse FT is done, which makes it an HRIR. If you run the changed code, the high-pass effect should become visible.

> No worries, I'll resend you the links!

thanks!

**Comment by f-brinkmann** [comment]
One possible source of error might be the referencing. If a wrong value is applied there, the HRTF magnitude would change.

**Comment by germknoedlspeck** [comment]
> > could it be that the old script calculated and saved the data in dB, maybe also including a normalisation to 20 µPa?
> 
> As far as I remember, we never referenced to 20 micro Pa.

Yes, sorry my mistake.


> > This is why we create two different SOFA Objects. I was talking about the HRIR-Object, the HRTF-Object is not affected by this. Also, we do not add 0 Hz for the HRTF-Object.
> 
> Its indeed added to the HRTF, but its not safed/returned. After adding it, the inverse FT is done, which makes it an HRIR. If you run the changed code, the high-pass effect should become visible.

I understand that you are talking about a filter in the frequency domain. However, in the HRTF.sofa object, we save raw pressure data without a) normalising it to anything (i.e., the transfer functions shows 0 dB for low frequencies) and b) saving 20*log(pressure./2e-5) dB Information.

The HRTF.sofa object created depicts pressure information, not "filter" in the signal processing sense.

**Comment by germknoedlspeck** [comment]
Are you using the HRTF.sofa object or the HRIR?

I have to use the HRIR object, because for further processing (e.g., using baumgartner2014 to compare different HRTFs), I need the time domain information (also, SOFAhrtf2dtf expects an IR).

**Comment by f-brinkmann** [comment]
I used the HRIRs in the plots above.

The HRTF.sofa objects should contain the pressure values (not dB) after referencing, i.e., absolute values should be close to 1 (0 dB) at low frequencies in the HRTF sofa files. This is not the case for the sanity check folder. So I assume something with the referencing is not working as intended.

If I run the project in Python everything looks fine, which also points to the referencing being the problem. In addition, python adds a '1' for 0 Hz, which suggests that this was not the problem. I still thing that not reverting the commit introduces errors.

I think debugging the referencing might reveal the bug - sorry for the brief response I'm on a long weekend vacation since an hour :)

**Comment by f-brinkmann** [comment]
Thought about it on the way home and found it and fixed it. Was the referencing as I assumed: 7c932c3912ea31139675cb53bcc36fa0323d9ded

Here is how the HRTF looks like if you add 0 (-inf dB) at 0 Hz. It only becomes visible with a linear frequency axis. I thus reverted the change.

![Screenshot 2022-10-20 173922](https://user-images.githubusercontent.com/58219902/196994701-16ce990d-bb02-4639-b7ec-6930ce281009.png)

**Comment by germknoedlspeck** [comment]
Thanks for the change! This explains the small pressure values I was wondering about.

Do I understand it correctly that the values we write to the HRTF (and later use for HRIR calculation) still correspond to pressure values and not logarithmic/dB values?

**Comment by f-brinkmann** [comment]
Yes linear pressure values, possibly referenced :)
