### ISSUE TITLE
add octave and third octave option in blender plugin

### ISSUE THREAD

**Issue by ahms5** [Any2HRTF/Mesh2HRTF#67]
the idea is to add two options in the frequnecy dropdown (`frequencyVectorType`) for third-ocatave and ocatve bands. `minFrequency`  and `maxFrequency` defines the limits and `frequencyVectorValue` is not needed in this case.

**Comment by f-brinkmann** [comment]
Implemented in https://pypi.org/project/mesh2scattering/
