### ISSUE TITLE
some tests fail with sofar 1.0.0

### ISSUE THREAD

**Issue by ahms5** [Any2HRTF/Mesh2HRTF#70]
some tests in tests_output.py fails due to version problems. for 0.3.1 they pass.

**Comment by f-brinkmann** [comment]
Yes, I'm already on it :) Its the same issue as here: https://github.com/pyfar/pyfar/issues/426

**Comment by f-brinkmann** [comment]
I fixed the files that I suspected to be the problem but won't have access to my Linux machine to test it until Tuesday. The new files are here: https://github.com/Any2HRTF/Mesh2HRTF/tree/bugfix/testing

**Comment by f-brinkmann** [comment]
The issue should now be resolved in develop. Please reopen, if you still get the error
