### ISSUE TITLE
Add references related to HRTFs and numerical simulations to the Wiki

### ISSUE THREAD

**Issue by SDX-LV** [Any2HRTF/Mesh2HRTF#79]
I would like to introduce and discuss some options / ideas how to make simulated HRTFs sound even more natural.
To get a bit of structure for the discussion, here is a diagram with some of the identified opportunities.

It looks something like this: 
[<img src="https://sourceforge.net/p/mesh2hrtf-tools/wiki/Mesh2HRTF%20options/attachment/2023-02-20%20Mesh2HRTF%20options.png" width="60%">](https://www.yworks.com/yed-live/?file=https://gist.githubusercontent.com/SDX-LV/d8d0bd749ad109deef5cba6878484777/raw/45705cddefedc7be4e36ca7ed55a47359f944001/Mesh2HRTF%20option%20diagram)

And the editable/exportable original is here: https://www.yworks.com/yed-live/?file=https://gist.githubusercontent.com/SDX-LV/d8d0bd749ad109deef5cba6878484777/raw/45705cddefedc7be4e36ca7ed55a47359f944001/Mesh2HRTF%20option%20diagram

**Comment by f-brinkmann** [comment]
While this is of course interesting. I don't see a strong connection to Mesh2HRTF and would suggest to have the discussion somewhere else. For lots of your points, there are studies that suggest a best practice or methods that can achieve the goal.

**Comment by SDX-LV** [comment]
You are right, there are studies and right here we have experts who know the answers, so the main idea is "Documentation Enhancment".
When someone (outside researchers that focus on HRTFs) tries to use Mesh2HRTF for practical auralization, they will likely read the existing Mesh2HRTF tutorials, which suggest something like this:

1. Simulate head only (or include shoulders if you like) with default "hrtf_mesh_grading" quality and using default skin material.
2. Microphones are point-sized and go into ear-plug locations.
3. Simulate Default evaluation grid and/or try some other evaluation grids.
4. Do not post-process the SOFA file at all (note, while HpTFs get smoothed and processed, the HRTF with all its notches is never filtered?).
5. For HpTF EQ: there are several different recommendations, but still a lot of confusion about what is a good enough or correct way to equalize HRTF to make it sound good enough for a listening experiment.
6. No reverb or room acoustics - you get the anechoic chamber sound and we hope you will not blame Mesh2HRTF for how unnatural it may sound (in case you can not evaluate Mesh2HRTF sound inside an actual anechoic chamber). 
7. Then we do have tutorials for beginners on how to test and listen to HRTFs.

* * *

Basically I would like to write more Documentation (with references to studies) and practical advice about:

- **Why Mesh2HRTF auralization does not sound like your reference listening room?** And what can be done to make a fair comparison to some loudspeaker? (because the best proof that Mesh2HRTF works is an A-B comparison to some real-life reference).
- Different suggestions about improving simulation results, for example, 
     - is there a practical benefit to use more elaborate materials than the default Mesh2HRTF skin material?
     - is there a benefit in deeper placement of Mesh2HRTF microphone into ear canal (as possible with a special 3D ear scanner)? Perhaps usage of multiple microphone locations around the ear canal entrance can improve robustness?
     - what post-processing (filtering, averaging, etc.) makes sense on the SOFA HRIR data before it is sent into convolver? In other words, are the HRIRs straight out of the Mesh2HRTF perfectly robust and without-any-noise to be directly auralized (with just HpTF EQ added in the end)? Note that measured-HRTFs usually have extensive post-processing applied to the raw measurement data.

Could you point me towards the most relevant research papers where I can find answers to these questions? I could then summarize the references into answers for these practical Mesh2HRTF user questions.

**Comment by f-brinkmann** [comment]
Ah, ok that makes sense. I put it on my list but I will need a few weeks. Can you  start a message with a checklist of topics? I could edit that to add references...

**Comment by f-brinkmann** [comment]
closed due to inactivity
