### ISSUE TITLE
Incorrect output HRIR data problem

### ISSUE THREAD

**Issue by babar414** [Any2HRTF/Mesh2HRTF#83]
I am using the example Kemar mesh (without Shoulders). I have gone through all the steps to generate the HRIRs and HRTFs. It seems the HRIR data is somehow jumping left and right when I listen to it on a DAW, and also the plot below seems to suggest the same.
![image](https://user-images.githubusercontent.com/17760771/222116220-15185625-7625-4753-a2e6-1014a8fa431f.png)

the HRTF files on the other hand seem fine when I listen to them.

I have tried generated the merged HRTF files using finalize_hrtf_simulation.py script as well as the mesh2hrtf API and running the method m2h.process_multiple_outputs2hrtf. Both give the same results.

**Comment by f-brinkmann** [comment]
Either, the HRIRs are not sorted correctly or there are problems with the numerical calculation. Might it be this problem: https://github.com/Any2HRTF/Mesh2HRTF/issues/78#issuecomment-1446003130

**Comment by f-brinkmann** [comment]
@babar414 we now fixed this in pyfar 0.5.3. Can you find some time to see if this really solved the issue?
