### ISSUE TITLE
Question about fe.out

### ISSUE THREAD

**Issue by LeinLabXIAN** [Any2HRTF/Mesh2HRTF#9]
Hi, Dr
My name is Robb, I'm a student in Acoustics, intested in Mesh2HRTF, I learned and verified your teaching video. However, a problem cannot be solved.

My  environment:  Unbantu 22.04, Mesh2HRTF V1.0.0, Blender2.91.20, Kemar model. Used "hrtf_mesh_grading" on Windows,and copied the processed stl back to Linux.
After NumCalcManager.py, in folder ../myHRTF_project_L(R)/NumCalc/source_1/, no fe.out output, 
others (be.out, NC.out, NClog.txt)  exist.
Please give me some guidance.Thank you!

**Comment by f-brinkmann** [comment]
Hi Rob,

that issue got fixed yesterday - everything should work again, if you pull the latest updates from the develop branch :)

Best, Fabian

**Comment by LeinLabXIAN** [comment]
Thank you, Dr.

After Mesh2HRTF updated, problem was solved, it works well.


________________________________
发件人: Fabian Brinkmann ***@***.***>
发送时间: 2022年5月17日 2:18
收件人: Any2HRTF/Mesh2HRTF ***@***.***>
抄送: LeinLabXIAN ***@***.***>; Author ***@***.***>
主题: Re: [Any2HRTF/Mesh2HRTF] Question about fe.out (Issue #9)


Hi Rob,

that issue got fixed yesterday - everything should work again, if you pull the latest updates from the develop branch :)

Best, Fabian

―
